# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DB_Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('points', models.IntegerField(blank=True)),
                ('point_type', models.CharField(blank=True, max_length=16)),
                ('completed', models.BooleanField()),
                ('priority', models.IntegerField(blank=True)),
                ('manual_rank', models.IntegerField(blank=True)),
                ('category_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.DB_Category')),
            ],
        ),
        migrations.CreateModel(
            name='DB_TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('canvas_course_id', models.CharField(blank=True, max_length=256)),
                ('service', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='DB_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('canvas_token', models.CharField(max_length=256)),
                ('canvas_id', models.CharField(max_length=256)),
                ('canvas_avatar_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='db_todolist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.DB_User'),
        ),
        migrations.AddField(
            model_name='db_tasks',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.DB_TodoList'),
        ),
        migrations.AddField(
            model_name='db_tasks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.DB_User'),
        ),
    ]
