# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_tasks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='db_tasks',
            old_name='list_id',
            new_name='todo_list',
        ),
        migrations.RenameField(
            model_name='db_tasks',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='db_todolist',
            old_name='canvas_course_id',
            new_name='canvas_course',
        ),
        migrations.RenameField(
            model_name='db_todolist',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='db_user',
            old_name='canvas_id',
            new_name='canvas',
        ),
    ]
