# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tasks_db_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DB_Due',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField(verbose_name='Due Date')),
            ],
            options={
                'db_table': 'tasks_db_due',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DB_Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256, verbose_name='Task Name')),
                ('start_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation Time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Due Date')),
                ('points', models.IntegerField(null=True, verbose_name='Points')),
                ('point_type', models.CharField(max_length=16, null=True, verbose_name='Type of Points')),
                ('completed', models.BooleanField(verbose_name='Is Completed?')),
                ('priority', models.IntegerField(null=True, verbose_name='Priority')),
                ('manual_rank', models.IntegerField(null=True, verbose_name='Manual Rank')),
                ('point_priority', models.FloatField(null=True, verbose_name='Point Priority')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvasplusplus.DB_Category', verbose_name='Category')),
            ],
            options={
                'db_table': 'tasks_db_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DB_TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='List Name')),
                ('color', models.CharField(max_length=16, null=True, verbose_name='List Color')),
                ('canvas_course', models.CharField(max_length=256, null=True, verbose_name='Canvas Course ID')),
                ('service', models.CharField(max_length=16, verbose_name='Service')),
            ],
            options={
                'db_table': 'tasks_db_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DB_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='Username')),
                ('canvas_token', models.CharField(max_length=256, null=True, verbose_name='Canvas Token')),
                ('canvas', models.CharField(max_length=256, null=True, verbose_name='Canvas ID')),
                ('canvas_avatar_url', models.CharField(max_length=256, null=True, verbose_name='Canvas Avatar URL')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auth User ID')),
            ],
            options={
                'db_table': 'tasks_db_tasks',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='db_todolist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasplusplus.DB_User', verbose_name='Owner ID'),
        ),
        migrations.AddField(
            model_name='db_tasks',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasplusplus.DB_TodoList', verbose_name='List'),
        ),
        migrations.AddField(
            model_name='db_tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvasplusplus.DB_User', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='db_due',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='canvasplusplus.DB_Tasks', verbose_name='Task Name'),
        ),
    ]
